<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="Syntax.fs" />
    <Compile Include="Reader.fs" />
    <Compile Include="Values.fs" />
    <Compile Include="Primitives.fs" />
    <Compile Include="Interpreter.fs" />
    <Compile Include="Prelude.fs" />
    <Compile Include="Engine.fs" />
  </ItemGroup>
</Project>
